project:
  type: website
  output-dir: docs

website:
  title: "Emma's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Portfolio.qmd
      - href: emmaresume.pdf
        text: Resume
      - walkthrough.qmd
      - href: epigeneticspaper.qmd
        text: Epigenetics Paper
      - href: roboticbees.qmd
        text: Robotic Bees Article
  page-footer: 
    left: "Copyright 2022, Emma Saaty" 
    right: 
      - icon: github
        href: https://github.com/emmasaaty
      - icon: twitter 
        href: https://twitter.com/EmmaS56963804

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    

