project:
  type: website
  output-dir: docs

website:
  title: "Emma's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Portfolio.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



