---
title: "Virginia Election Project"
author: "Emma Saaty"
execute:
  echo: true
format:
  html:
    self-contained: true
    code-tools: true
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}


library(tidyverse)
library(janitor)
library(httr)
library(jsonlite)
library(kableExtra)
library(here)
options(scipen = 999)
options(stringsAsFactors = FALSE)


#load saved joined data file from previous script
joined_vacomparison <- readRDS(here("processed_data", "joined_vacomparison.rds"))



```

# Comparing Virgnia Gov vs. Prez

```{r}

head(joined_vacomparison)


```

```{r}

biggestyoungkinlosses <- joined_vacomparison %>%
  mutate(RminusD = pct_youngkin - pct_mcauliffe) %>%
  select(locality, pct_youngkin, pct_mcauliffe, RminusD) %>%
  arrange(RminusD) %>%
  head(5)

DT::datatable(biggestyoungkinlosses)
```

```{r}
ggplot(biggestyoungkinlosses, aes (x = reorder(locality, RminusD), y = RminusD))+
  geom_col(color = "#9ebcda")+
  scale_y_reverse(name = "Percentage of Votes Youngkin Lost to Mcauliffe")+
  scale_x_discrete(name = "Localities")+
theme(axis.text.x = element_text(angle = 10))

```

```{r}
youngkin_over_trump <- joined_vacomparison %>%
  mutate(youngkin_minus_trump = pct_youngkin - trump_pct) %>%
  select(locality, pct_youngkin, trump_pct, youngkin_minus_trump) %>%
  arrange(desc(youngkin_minus_trump)) %>%
  head(5)

DT::datatable(youngkin_over_trump)
```

```{r}
ggplot(youngkin_over_trump, aes (x = reorder(locality, youngkin_minus_trump), y = youngkin_minus_trump))+
  geom_col(color = "#9ebcda")+
  scale_y_continuous(name = "Percent of Youngkin's Votes over Trump's")+
  scale_x_discrete(name = "Localities")+
theme(axis.text.x = element_text(angle = 10))
```

```{r}
biden_over_mcauliffe <- joined_vacomparison %>%
  mutate(biden_minus_mcauliffe = biden_pct - pct_mcauliffe) %>%
  select(locality, biden_pct, pct_mcauliffe, biden_minus_mcauliffe) %>%
  arrange(desc(biden_minus_mcauliffe)) %>%
  head(5)

DT::datatable(biden_over_mcauliffe)
```

```{r}
ggplot(biden_over_mcauliffe, aes (x = reorder(locality, biden_minus_mcauliffe), y = biden_minus_mcauliffe))+
  geom_col(color = "#9ebcda")+
  scale_y_continuous(name = "Percent of Biden's Votes over Mcauliffe's")+
  scale_x_discrete(name = "Localities")+
  theme(axis.text.x = element_text(angle = 10))
```
